version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: floodsense-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: floodsense-frontend
    depends_on:
      - backend
    environment:
      - FLOODSENSE_BACKEND_URL=http://backend:8000
    ports:
      - "8501:8501"

